health-multiplier: 1.03

mitosis: true

drops:
  tier1_drop:
    - item: "copper"
      amount: 20
    - item: "lead"
      amount: 20
    - item: "silicon"
      amount: 5
    - type: "random"
      items:
        - item: "graphite"
          amount: 10
        - item: "metaglass"
          amount: 5
        - item: "titanium"
          amount: 10

  tier2_drop:
    - item: "copper"
      amount: 30
    - item: "lead"
      amount: 30
    - item: "silicon"
      amount: 10
    - type: "random"
      items:
        - item: "graphite"
          amount: 20
        - item: "metaglass"
          amount: 10
        - item: "titanium"
          amount: 20

  tier3_drop:
    - item: "copper"
      amount: 50
    - item: "lead"
      amount: 50
    - item: "silicon"
      amount: 30
    - item: "phase-fabric"
      amount: 3
    - item: "surge-alloy"
      amount: 3
    - type: "random"
      items:
        - item: "graphite"
          amount: 30
        - item: "metaglass"
          amount: 20
        - item: "titanium"
          amount: 30
        - item: "plastanium"
          amount: 50
        - item: "thorium"
          amount: 50

  tier4_drop:
    - item: "copper"
      amount: 200
    - item: "lead"
      amount: 200
    - item: "silicon"
      amount: 50
    - item: "phase-fabric"
      amount: 20
    - item: "surge-alloy"
      amount: 40
    - type: "random"
      items:
        - item: "graphite"
          amount: 30
        - item: "metaglass"
          amount: 30
        - item: "titanium"
          amount: 30
        - item: "plastanium"
          amount: 80
        - item: "thorium"
          amount: 80

  tier5_drop:
    - item: "copper"
      amount: 300
    - item: "lead"
      amount: 300
    - item: "silicon"
      amount: 100
    - item: "phase-fabric"
      amount: 30
    - item: "surge-alloy"
      amount: 60
    - type: "random"
      items:
        - item: "graphite"
          amount: 40
        - item: "metaglass"
          amount: 40
        - item: "titanium"
          amount: 40
        - item: "plastanium"
          amount: 120
        - item: "thorium"
          amount: 120

units:
  # Dagger Tree
  dagger:
    drop: "tier1_drop"
  mace:
    drop: "tier2_drop"
    downgrade: "dagger"
  fortress:
    drop: "tier3_drop"
    downgrade: "mace"
  scepter:
    drop: "tier4_drop"
    downgrade: "fortress"
  reign:
    drop: "tier5_drop"
    downgrade: "scepter"

  # Crawler Tree
  crawler:
    drop: "tier1_drop"
  atrax:
    drop: "tier2_drop"
    downgrade: "crawler"
  spiroct:
    drop: "tier3_drop"
    downgrade: "atrax"
  arkyid:
    drop: "tier4_drop"
    downgrade: "spiroct"
  toxopid:
    drop: "tier5_drop"
    downgrade: "arkyid"

  # Nova Tree
  nova:
    drop: "tier1_drop"
  pulsar:
    drop: "tier2_drop"
    downgrade: "nova"
  quasar:
    drop: "tier3_drop"
    downgrade: "pulsar"
  vela:
    drop: "tier4_drop"
    downgrade: "quasar"
  corvus:
    drop: "tier5_drop"
    downgrade: "vela"

  # Mono Tree
  mono:
    drop: "tier1_drop"
  poly:
    drop: "tier2_drop"
    downgrade: "mono"
  mega:
    drop: "tier3_drop"
    downgrade: "poly"
  quad:
    drop: "tier4_drop"
    downgrade: "mega"
  oct:
    drop: "tier5_drop"
    downgrade: "quad"

  # Flare Tree
  flare:
    drop: "tier1_drop"
  horizon:
    drop: "tier2_drop"
    downgrade: "flare"
  zenith:
    drop: "tier3_drop"
    downgrade: "horizon"
  antumbra:
    drop: "tier4_drop"
    downgrade: "zenith"
  eclipse:
    drop: "tier5_drop"
    downgrade: "antumbra"
