game-mode: "tower-defense"

tower-defense:
  health-multiplier: 1.03

  drops:

    tier1_drop:
      - item: "copper"
        amount: 20
      - item: "lead"
        amount: 20
      - item: "silicon"
        amount: 5
      - type: "random"
        items:
          - item: "graphite"
            amount: 10
          - item: "metaglass"
            amount: 5
          - item: "titanium"
            amount: 10

    tier2_drop:
      - item: "copper"
        amount: 30
      - item: "lead"
        amount: 30
      - item: "silicon"
        amount: 10
      - type: "random"
        items:
          - item: "graphite"
            amount: 20
          - item: "metaglass"
            amount: 10
          - item: "titanium"
            amount: 20

    tier3_drop:
      - item: "copper"
        amount: 50
      - item: "lead"
        amount: 50
      - item: "silicon"
        amount: 30
      - item: "phase-fabric"
        amount: 3
      - item: "surge-alloy"
        amount: 3
      - type: "random"
        items:
          - item: "graphite"
            amount: 30
          - item: "metaglass"
            amount: 20
          - item: "titanium"
            amount: 30
          - item: "plastanium"
            amount: 50
          - item: "thorium"
            amount: 50

    tier4_drop:
      - item: "copper"
        amount: 200
      - item: "lead"
        amount: 200
      - item: "silicon"
        amount: 50
      - item: "phase-fabric"
        amount: 20
      - item: "surge-alloy"
        amount: 40
      - type: "random"
        items:
          - item: "graphite"
            amount: 30
          - item: "metaglass"
            amount: 30
          - item: "titanium"
            amount: 30
          - item: "plastanium"
            amount: 80
          - item: "thorium"
            amount: 80

    tier5_drop:
      - item: "copper"
        amount: 300
      - item: "lead"
        amount: 300
      - item: "silicon"
        amount: 100
      - item: "phase-fabric"
        amount: 30
      - item: "surge-alloy"
        amount: 60
      - type: "random"
        items:
          - item: "graphite"
            amount: 40
          - item: "metaglass"
            amount: 40
          - item: "titanium"
            amount: 40
          - item: "plastanium"
            amount: 120
          - item: "thorium"
            amount: 120

  units:
    # Tier 1
    dagger:
      drop: "tier1_drop"
    crawler:
      drop: "tier1_drop"
    nova:
      drop: "tier1_drop"
    mono:
      drop: "tier1_drop"
    flare:
      drop: "tier1_drop"

    # Tier 2
    mace:
      drop: "tier2_drop"
    atrax:
      drop: "tier2_drop"
    pulsar:
      drop: "tier2_drop"
    poly:
      drop: "tier2_drop"
    horizon:
      drop: "tier2_drop"

    # Tier 3
    fortress:
      drop: "tier3_drop"
    spiroct:
      drop: "tier3_drop"
    quasar:
      drop: "tier3_drop"
    mega:
      drop: "tier3_drop"
    zenith:
      drop: "tier3_drop"

    # Tier 4
    scepter:
      drop: "tier4_drop"
    arkyid:
      drop: "tier4_drop"
    vela:
      drop: "tier4_drop"
    quad:
      drop: "tier4_drop"
    antumbra:
      drop: "tier4_drop"

    # Tier 5
    reign:
      drop: "tier5_drop"
    toxopid:
      drop: "tier5_drop"
    corvus:
      drop: "tier5_drop"
    oct:
      drop: "tier5_drop"
    eclipse:
      drop: "tier5_drop"
